const symbolButtons = [
  {
    name: 'Limit',
    value: '\\lim\\limits_{x \\to y} f(x)',
    imgSrc: '/assets/img/main-functions/limit.svg',
    section: 'Main Functions',
    width: '40px'

  },
  {
    name: 'Integral',
    value: '\\int ',
    imgSrc: '/assets/img/main-functions/integral.svg',
    section: 'Main Functions',
    width: '11px',
  },
  {
    name: 'Productory',
    value: '\\prod_{i}^{k} ',
    imgSrc: '/assets/img/main-functions/product.svg',
    section: 'Main Functions',
  },
  {
    name: 'Summation',
    value: '\\sum_{i}^{k} ',
    imgSrc: '/assets/img/main-functions/summation.svg',
    section: 'Main Functions',
  },
  {
    name: 'Direct Limit',
    value: '\\varinjlim_{i} ',
    imgSrc: '/assets/img/main-functions/direct-limit.svg',
    section: 'Main Functions',
  },
  {
    name: 'Integral With Variables',
    value: '\\int_{a}^{b} ',
    imgSrc: '/assets/img/main-functions/var-integral.svg',
    section: 'Main Functions',
    width: '15px',
  },
  {
    name: 'Coproduct',
    value: '\\coprod ',
    imgSrc: '/assets/img/main-functions/coproduct.svg',
    section: 'Main Functions',
  },
  {
    name: 'Surface Integral',
    value: '\\iint ',
    imgSrc: '/assets/img/main-functions/surface-integral.svg',
    section: 'Main Functions',
    width: '15px',
  },
  {
    name: 'Limit Superior',
    value: '\\varlimsup', // Substituído de \varlimsup (não suportado no KaTeX)
    imgSrc: '/assets/img/main-functions/limit-superior.svg',
    section: 'Main Functions',
  },
  {
    name: 'Volume Integral',
    value: '\\iiint ',
    imgSrc: '/assets/img/main-functions/volume-integral.svg',
    section: 'Main Functions',
    width: '20px',
  },
  {
    name: 'Limit Inferior',
    value: '\\varliminf  ', // Substituído de \varliminf (não suportado no KaTeX)
    imgSrc: '/assets/img/main-functions/limit-inferior.svg',
    section: 'Main Functions',
  },
  {
    name: 'Curve Integral',
    value: '\\oint ',
    imgSrc: '/assets/img/main-functions/curve-integral.svg',
    section: 'Main Functions',
    width: '13px',
  },
  {
    name: 'Logarithm',
    value: '\\log_{b}{n} ',
    imgSrc: '/assets/img/basic-operations/logarithm.svg',
    section: 'Basic Operations',
    width: '30px',
  
  },
  {
    name: '1st Function',
    value: 'f(x) ',
    imgSrc: '/assets/img/basic-operations/function.svg',
    section: 'Basic Operations',
    width: '30px',
  },
  {
    name: 'Square Root',
    value: '\\sqrt{} ',
    imgSrc: '/assets/img/basic-operations/square-root.svg',
    section: 'Basic Operations',
  },
  {
    name: 'Fraction',
    value: '\\frac{a}{b} ',
    imgSrc: '/assets/img/basic-operations/division.svg',
    section: 'Basic Operations',
    width: '10px',
  },
  {
    name: 'Real Number',
    value: '\\mathbb{R} ',
    imgSrc: '/assets/img/number-sets/real-number.svg',
    section: 'Number Sets',
  },
  {
    name: 'Complex Number',
    value: '\\mathbb{C} ',
    imgSrc: '/assets/img/number-sets/complex-number.svg',
    section: 'Number Sets',
  },
  {
    name: 'Natural Number',
    value: '\\mathbb{N} ',
    imgSrc: '/assets/img/number-sets/natural-number.svg',
    section: 'Number Sets',
  },
  {
    name: 'Rational Number',
    value: '\\mathbb{Q} ',
    imgSrc: '/assets/img/number-sets/rational-number.svg',
    section: 'Number Sets',
  },
  {
    name: 'Integer Number',
    value: '\\mathbb{Z} ',
    imgSrc: '/assets/img/number-sets/integer.svg',
    section: 'Number Sets',
  },
  {
    name: 'Pi',
    value: '\\pi ',
    imgSrc: '/assets/img/constants/pi.svg',
    section: 'Constants',
  },
  {
    name: 'Lambda',
    value: '\\lambda ',
    imgSrc: '/assets/img/constants/lambda.svg',
    section: 'Constants',
  },
  {
    name: 'Euler',
    value: 'e ',
    imgSrc: '/assets/img/constants/euler.svg',
    section: 'Constants',
  },
  {
    name: 'Einstein Gravitational',
    value: '\\kappa ',
    imgSrc: '/assets/img/constants/eistein-gravitational.svg',
    section: 'Constants',
  },
  {
    name: 'Euler-Mascheroni',
    value: '\\gamma ',
    imgSrc: '/assets/img/constants/euler-mascheroni.svg',
    section: 'Constants',
  },
  {
    name: 'Imaginary Unit',
    value: '\\mathrm{i} ',
    imgSrc: '/assets/img/constants/imaginary-unit.svg',
    section: 'Constants',
  },
  {
    name: 'Prouhet-Thue-Morse',
    value: '\\tau ',
    imgSrc: '/assets/img/constants/prouhet-thue-morse.svg',
    section: 'Constants',
  },
  {
    name: 'Ramanujan-Soldner',
    value: '\\mu ',
    imgSrc: '/assets/img/constants/ramanujan-soldner.svg',
    section: 'Constants',
  },
  {
    name: 'Somos Quadratic Recurrence',
    value: '\\sigma ',
    imgSrc: '/assets/img/constants/somos-quadratic-recurrence.svg',
    section: 'Constants',
  },
  {
   

 name: 'Golden Ratio',
    value: '\\phi ',
    imgSrc: '/assets/img/constants/golden-radio.svg',
    section: 'Constants',
  },
  {
    name: 'Infinity',
    value: '\\infty ',
    imgSrc: '/assets/img/constants/infinity.svg',
    section: 'Constants',
  },
  {
    name: 'Theta',
    value: '\\theta ',
    imgSrc: '/assets/img/constants/thetha.svg',
    section: 'Constants',
  },
  {
    name: 'Vacuum Permittivity',
    value: '\\epsilon ',
    imgSrc: '/assets/img/constants/vacuum-permittivity.svg',
    section: 'Constants',
  },
  {
    name: 'Delta',
    value: '\\Delta ',
    imgSrc: '/assets/img/constants/delta.svg',
    section: 'Constants',
  },
  {
    name: 'Logical Conjunction',
    value: '\\land ',
    imgSrc: '/assets/img/logic/logical-conjunction.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Logical Disjunction',
    value: '\\lor ',
    imgSrc: '/assets/img/logic/logical-disjunction.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Logical Equivalence Short',
    value: '\\Leftrightarrow ',
    imgSrc: '/assets/img/logic/logical-equivalence-short.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Logical Equivalence Long',
    value: '\\iff ',
    imgSrc: '/assets/img/logic/logical-equivalence-long.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Contradiction',
    value: '\\bot ',
    imgSrc: '/assets/img/logic/contradiction.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Deductive Reasoning',
    value: '\\therefore ',
    imgSrc: '/assets/img/logic/deductive-reasoning.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Existential Quantification',
    value: '\\exists ',
    imgSrc: '/assets/img/logic/existential-quantification.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Logical Negation',
    value: '\\lnot ',
    imgSrc: '/assets/img/logic/logical-negation.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Logical Equivalence Single',
    value: '\\leftrightarrow ',
    imgSrc: '/assets/img/logic/logical-equivalence-single.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Short Right Arrow',
    value: '\\rightarrow ',
    imgSrc: '/assets/img/logic/short-right-arrow.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Tautology',
    value: '\\top ',
    imgSrc: '/assets/img/logic/tautology.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Uniqueness Quantification',
    value: '\\exists! ',
    imgSrc: '/assets/img/logic/uniqueness-quantification.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Universal Quantification',
    value: '\\forall ',
    imgSrc: '/assets/img/logic/universal-quantification.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Exclusive Or',
    value: '\\veebar ',
    imgSrc: '/assets/img/logic/exclusive-or.svg',
    section: 'Logical Operations',
  },
  {
    name: 'Intersection Small',
    value: '\\cap ',
    imgSrc: '/assets/img/set-operations/intersection-small.svg',
    section: 'Set Operations',
  },
  {
    name: 'Union Small',
    value: '\\cup ',
    imgSrc: '/assets/img/set-operations/union-small.svg',
    section: 'Set Operations',
  },
  {
    name: 'Element Of',
    value: '\\in ',
    imgSrc: '/assets/img/set-operations/in.svg',
    section: 'Set Operations',
  },
  {
    name: 'Not Element Of',
    value: '\\notin ',
    imgSrc: '/assets/img/set-operations/not-in.svg',
    section: 'Set Operations',
  },
  {
    name: 'Subset',
    value: '\\subset ',
    imgSrc: '/assets/img/set-operations/subset.svg',
    section: 'Set Operations',
  },
  {
    name: 'Not Subset',
    value: '\\not\\subset ',
    imgSrc: '/assets/img/set-operations/not-subset.svg',
    section: 'Set Operations',
  },
  {
    name: 'Left Arrow',
    value: '\\leftarrow ',
    imgSrc: '/assets/img/arrows/left-arrow.svg',
    section: 'Arrows',
  },
  {
    name: 'Right Arrow',
    value: '\\rightarrow ',
    imgSrc: '/assets/img/arrows/right-arrow.svg',
    section: 'Arrows',
  },
  {
    name: 'Long Left Arrow',
    value: '\\longleftarrow ',
    imgSrc: '/assets/img/arrows/long-left-arrow.svg',
    section: 'Arrows',
  },
  {
    name: 'Long Right Arrow',
    value: '\\longrightarrow ',
    imgSrc: '/assets/img/arrows/long-right-arrow.svg',
    section: 'Arrows',
  },
  {
    name: 'Lesser Than',
    value: '\\lt ',
    imgSrc: '/assets/img/arithmetic-comparison/lesser-than.svg',
    section: 'Comparison',
  },
  {
    name: 'Equality',
    value: '= ',
    imgSrc: '/assets/img/arithmetic-comparison/equality.svg',
    section: 'Comparison',
  },
  {
    name: 'Greater Than',
    value: '> ',
    imgSrc: '/assets/img/arithmetic-comparison/greater-than.svg',
    section: 'Comparison',
  },
  {
    name: 'Plus Minus',
    value: '\\pm ',
    imgSrc: '/assets/img/arithmetic-comparison/plus-minus.svg',
    section: 'Comparison',
  },
  {
    name: 'Less Equal',
    value: '\\leq ',
    imgSrc: '/assets/img/arithmetic-comparison/leqslant.svg',
    section: 'Comparison',
  },
  {
    name: 'Identity',
    value: '\\equiv ',
    imgSrc: '/assets/img/arithmetic-comparison/identity.svg',
    section: 'Comparison',
  },
  {
    name: 'Greater Equal',
    value: '\\geq ',
    imgSrc: '/assets/img/arithmetic-comparison/geqslant.svg',
    section: 'Comparison',
  },
  {
    name: 'Less Approx',
    value: '\\lessapprox ',
    imgSrc: '/assets/img/arithmetic-comparison/lessapprox.svg',
    section: 'Comparison',
  },
  {
    name: 'Approximation',
    value: '\\approx ',
    imgSrc: '/assets/img/arithmetic-comparison/approximation.svg',
    section: 'Comparison',
  },
  {
    name: 'Greater Approx',
    value: '\\gtrapprox ',
    imgSrc: '/assets/img/arithmetic-comparison/gtrapprox.svg',
    section: 'Comparison',
  },
  {
    name: 'Less Less',
    value: '\\ll ',
    imgSrc: '/assets/img/arithmetic-comparison/lessless.svg',
    section: 'Comparison',
  },
  {
    name: 'Equivalence Class',
    value: '\\sim ', // Ajustado, pois \ll parece incorreto no original
    imgSrc: '/assets/img/arithmetic-comparison/equivalence-class.svg',
    section: 'Comparison',
  },
  {
    name: 'Greater Greater',
    value: '\\gg ', // Ajustado, pois \ll parece incorreto no original
    imgSrc: '/assets/img/arithmetic-comparison/gg.svg',
    section: 'Comparison',
  },
  {
    name: 'Brackets Matrix',
    value: '\\begin{bmatrix}a & b \\\\ c & d\\end{bmatrix} ',
    imgSrc: '/assets/img/matrices-and-vectors/brackets-matrix.svg',
    section: 'Matrices',
  },
  {
    name: 'Braces Matrix',
    value: '\\begin{Bmatrix}a & b \\\\ c & d\\end{Bmatrix} ',
    imgSrc: '/assets/img/matrices-and-vectors/keys-matrix.svg',
    section: 'Matrices',
  },
  {
    name: 'Pipes Matrix',
    value: '\\begin{vmatrix}a & b \\\\ c & d\\end{vmatrix} ',
    imgSrc: '/assets/img/matrices-and-vectors/vert-matrix.svg',
    section: 'Matrices',
  },
  {
    name: 'Parentheses Matrix',
    value: '\\begin{pmatrix}a & b \\\\ c & d\\end{pmatrix} ',
    imgSrc: '/assets/img/matrices-and-vectors/parentheses-matrix.svg',
    section: 'Matrices',
  },
  {
    name: 'Linear System',
    value: '\\begin{cases} a_{1}x + b_{1}y = c1 \\end{cases}  ',
    imgSrc: '/assets/img/matrices-and-vectors/linear-system.svg',
    section: 'Linear System',

  },
  {
    name: 'Sine',
    value: '\\sin ',
    imgSrc: '/assets/img/trigonometry/sin.svg',
    section: 'Trigonometry',
  },
  {
    name: 'Cosine',
    value: '\\cos ',
    imgSrc: '/assets/img/trigonometry/cos.svg',
    section: 'Trigonometry',
  },
  {
    name: 'Tangent',
    value: '\\tan ',
    imgSrc: '/assets/img/trigonometry/tan.svg',
    section: 'Trigonometry',
  },
];

export default symbolButtons;